[tool.poetry]
name = "python-reversi"
version = "0.1.0"
description = ""
authors = ["Yuki Fujita <uni22yu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
black = "^24.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
